### ISSUE TITLE
Can't download image 20.03.1-py3 on Kind k8s 1.15.11

### ISSUE THREAD

**Issue by cliveseldon** [NVIDIA/triton-inference-server#1722]
**Description**

image `nvcr.io/nvidia/tritonserver:20.03.1-py3` cannot be downloaded on Kind 1.15.11
See https://github.com/kubernetes-sigs/kind/issues/1692 where it is suggested this is an issue with the repository `nvcr.io`.
Works on Kind 1.15.0

Background issue: https://github.com/containerd/containerd/issues/3556

**Triton Information**
What version of Triton are you using?
20.03.1-py3

**To Reproduce**
Steps to reproduce the behavior.

```
kind create cluster  --image kindest/node:v1.15.11
```
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: triton-simple
spec:
  containers:
  - args:
    - /opt/tritonserver/bin/tritonserver
    - --grpc-port=2001
    - --http-port=9000
    - --model-repository=/mnt/models
    - --api-version=2
    image: nvcr.io/nvidia/tritonserver:20.03.1-py3
    imagePullPolicy: IfNotPresent
    name: simple
    ports:
    - containerPort: 2001
      name: grpc
      protocol: TCP
    - containerPort: 9000
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /v2/health/ready
        port: http
        scheme: HTTP
    volumeMounts:
    - mountPath: /mnt/models
      name: simple-provision-location
      readOnly: true
  initContainers:
  - args:
    - gs://seldon-models/trtis/simple-model
    - /mnt/models
    image: gcr.io/kfserving/storage-initializer:0.2.2
    imagePullPolicy: IfNotPresent
    name: simple-model-initializer
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/models
      name: simple-provision-location
  volumes:
  - emptyDir: {}
    name: simple-provision-location
EOF
```

**Expected behavior**

Image can be pulled.
