### ISSUE TITLE
Jetson Triton v1 to v2 Tensorflow 

### ISSUE THREAD

**Issue by jishminor** [NVIDIA/triton-inference-server#1814]
**Description**
When moving from the v1 version of triton to v2, ssd_mobilenet_v1_coco is failing during model execution with error:
```
2020-07-21 21:25:33.666641: E tensorflow/core/common_runtime/executor.cc:648] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'explicit_paddings' not in Op<name=DepthwiseConv2dNative; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_BFLOAT16, DT_FLOAT, DT_DOUBLE]; attr=strides:list(int); attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]; attr=dilations:list(int),default=[1, 1, 1, 1]>; NodeDef: {{node FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_depthwise/BatchNorm/batchnorm/mul_1}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_depthwise/BatchNorm/batchnorm/mul_1]]
```

**Triton Information**
What version of Triton are you using?
Moved from release 1.12 to 2.0.0

Are you using the Triton container or did you build it yourself?
I built my own container using the triton tarball release for jetpack

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
Configuration:
```yaml
name: "ssd_mobilenet_coco"
platform: "tensorflow_graphdef"
max_batch_size: 1
input [
  {
    name: "image_tensor"
    data_type: TYPE_UINT8
    format: FORMAT_NHWC
    dims: [ 300, 300, 3 ]
  }
]
output [
  {
    name: "detection_boxes"
    data_type: TYPE_FP32
    dims: [ 100, 4 ]
  },
  {
    name: "detection_scores"
    data_type: TYPE_FP32
    dims: [ 100 ]
  },
  {
    name: "num_detections"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
  },
  {
    name: "detection_classes"
    data_type: TYPE_FP32
    dims: [ 100 ]
  }
]
```
**Expected behavior**
Moving from v1 to v2 shouldn't affect the behavior of calls to tensorflow, as at least according to the release notes, both releases of jetpack triton support Tensorflow 1.15.2.
